version: "3"

services:
  kogito-mongodb:
    container_name: kogito-mongodb
    image: quay.io/dmartino/mongo:4.4.9
    ports:
      - "27017:27017"

  postgres-compose:
    image: quay.io/dmartino/postgres:9.6
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/postgresql/data:/var/lib/postgresql/data
      - ./postgres/sql:/docker-entrypoint-initdb.d/
    networks:
      - postgres-compose-network
    container_name: postgres-container

  postgres-compose-podman:
    image: registry.redhat.io/rhel8/postgresql-10:1-157
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - ./postgres/sql:/postgresql-init/
    container_name: postgres-container

  pgadmin-compose:
    image: quay.io/dmartino/pgadmin4:5.0
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.org
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - 8055:80
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
    container_name: pgadmin-container

  infinispan:
    image: infinispan/server:11.0.4.Final
    container_name: infinispan
    ports:
      - 11222:11222
    command: "/opt/infinispan/bin/server.sh -c infinispan-demo.xml"
    volumes:
      - ./infinispan/infinispan.xml:/opt/infinispan/server/conf/infinispan-demo.xml:z
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11222/rest/v2/cache-managers/default/health/status" ]
      interval: 1s
      timeout: 1s
      retries: 50


networks:
  postgres-compose-network:
    driver: bridge