apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kogito-kafka
spec:
  kafka:
    replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    storage:
      type: ephemeral
    jvmOptions:
      gcLoggingEnabled: false
    config:
      log.message.format.version: 2.2
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
      auto.create.topics.enable: true
  zookeeper:
    replicas: 2
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}