apiVersion: v1
kind: Secret
metadata:
  name: kogito-mongodb-admin-developer
type: Opaque
stringData:
  "connectionString.standard": "mongodb://<UserName created using Ops Manager UI>:<Password created using Ops Manager UI>@kogito-sharded-mongo-mongos-0.kogito-sharded-mongo-svc.mongodb.svc.cluster.local,kogito-sharded-mongo-mongos-1.kogito-sharded-mongo-svc.mongodb.svc.cluster.local,kogito-sharded-mongo-mongos-2.kogito-sharded-mongo-svc.mongodb.svc.cluster.local,kogito-sharded-mongo-mongos-3.kogito-sharded-mongo-svc.mongodb.svc.cluster.local:27017/admin?ssl=false"
  "connectionString.standardSrv": "mongodb+srv://<UserName created using Ops Manager UI>:<Password created using Ops Manager UI>@kogito-sharded-mongo-svc.kogito-benchmark.svc.cluster.local/admin?ssl=false"
  "password": "<Password created using Ops Manager UI>"
  "username": "<UserName created using Ops Manager UI>"